name: Typescript
on:
  workflow_call:
  pull_request:
    branches:
      - main
      - staging
jobs:
  build:
    name: Typescript
    runs-on: ubuntu-latest
    env:
      API_URL: ${{secrets.API_URL}}
      NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Check Typescript files
        run: npm run build
